### ISSUE TITLE
No text written in some cases

### ISSUE THREAD

**Issue by Apostolique** [impeccableaslan/LoLvoice#1]
I'm using the IBM profile. At first all the text I say will be written. After a while, I see that the text box gets toggled (but not always), but no text gets written. If I wait a bit, it restarts working. Eventually it will break again. I'm not yet sure how to reproduce this.

**Comment by acyclics** [comment]
Thanks for finding the bug. I believe I have fixed this bug and have released a new setup file for LoLvoice with this bug fixed. It can be found [here](https://github.com/impeccableaslan/LoLvoice/releases/tag/v1.0.1). Please try it out and see if the bug is fixed on your end.

**Comment by Apostolique** [comment]
I will test more, but so far so good.
